name: Deploy
on:
  push:
    branches:
      - 'main'

concurrency:
  group: deploy-${{ github.head_ref }}
  cancel-in-progress: true
  
jobs:
  handbook:
    name: Handbook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --local-only --build-arg MIX_ENV=prod
  proxy-deploy:
    name: Proxy
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - uses: jdx/mise-action@v2
        with:
            experimental: true
      - run: mise run install
      - run: mise run deploy